customhost = "employee.cfbelnmn2a6i.us-east-1.rds.amazonaws.com"
customuser = "shambhuraj"
custompass = "EmployeeDatabase"
customdb = "employee"
custombucket = "addemployees1"
customregion = "us-east-1"
